"use client";

import { useState } from "react";
import { Brand } from "../components/brand";
import { ProductVessel } from "../components/product-vessel";

const Icon = ({ children }: { children: string }) => <span className="icon" aria-hidden="true">{children}</span>;
const benefits = [["◈", "Reliable Protection", "Excellent wear protection and engine cleanliness."], ["◉", "High Performance", "Consistent power and efficiency in all operating conditions."], ["♨", "Temperature Stability", "Performs in high temperatures and harsh marine environments."], ["✓", "Quality Assured", "Meets industry standards for marine engines."]];

export default function Home() {
  const [open, setOpen] = useState(false);
  return <main id="home">
    <header className="header"><Brand /><button className="nav-toggle" onClick={() => setOpen(!open)} aria-expanded={open} aria-controls="primary-navigation"><span /><span /><span /></button><nav id="primary-navigation" className={open ? "nav nav--open" : "nav"}><a className="active" href="#home">Home</a><a href="#about">About Us</a><a href="#products">Products</a><a href="#why">Why Sanga Oil</a><a href="#contact">Contact Us</a></nav><a href="#contact" className="button button--nav">Get in Touch</a></header>

    <section className="hero"><div className="hero__coast" /><div className="hero__water" /><div className="wrap hero__wrap"><div className="hero__copy reveal"><h1>Powering Performance.<br />Protecting Your Journey.</h1><i className="gold-line" /><p>Sanga Oil Limited produces high quality Outboard marine &amp; vessel engine oils built for reliability, protection and maximum performance.</p><div className="hero__promises"><div><Icon>◇</Icon><span><b>Superior Protection</b><small>Engine durability you can trust.</small></span></div><div><Icon>⚙</Icon><span><b>Optimal Performance</b><small>Smooth operation, every time.</small></span></div></div></div><div className="hero__products" aria-hidden="true"><div className="motor">250</div><div className="hero__drum"><i>S</i><b>SANGA OIL</b><small>OUTBOARD MARINE &amp;<br />VESSEL ENGINE OIL</small></div><ProductVessel grade="2T" size="hero" /><ProductVessel grade="4T" size="hero" /></div></div></section>

    <section className="benefits wrap section" id="why"><p className="eyebrow">ENGINEERED FOR THE WATER. TRUSTED ON EVERY JOURNEY.</p><i className="gold-line gold-line--center" /><div className="benefits__grid">{benefits.map(([symbol, title, description]) => <article className="reveal" key={title}><Icon>{symbol}</Icon><h2>{title}</h2><p>{description}</p></article>)}</div></section>

    <section className="products section" id="products"><div className="wrap"><div className="section-title"><p className="eyebrow eyebrow--gold">OUR PRODUCTS</p><h2>Two Formulations. Maximum Protection.</h2></div><div className="product-grid"><ProductCard grade="2T" formula="TC-W3" badge="For Smaller Engines" api="API SL" equivalent="Equivalent to 20W40" description="High quality 2-Stroke oil designed for outboard motors and smaller marine engines." /><ProductCard grade="4T" formula="FC-W" badge="For Bigger Engines" api="API SM" equivalent="Equivalent to 25W40" description="Premium 4-Stroke oil for powerful outboard and inboard marine engines." /></div></div></section>

    <section className="sizes section wrap"><p className="eyebrow eyebrow--gold">AVAILABLE PACK SIZES</p><h2>Available in 3 Convenient Sizes</h2><div className="sizes__grid"><Size name="4L" copy="Perfect for small engines and personal use." visual="bottle" /><Size name="25L" copy="Ideal for regular use and marine operators." visual="vessel" /><Size name="208L" copy="Economic choice for commercial and industrial use." visual="drum" /></div></section>

    <section className="regions" id="about"><div className="regions__copy"><p className="eyebrow">Proudly Serving</p><h2>Nigeria &amp; Cameroon</h2><p>Sanga Oil Limited is committed to powering marine operations across Nigeria and Cameroon with quality you can rely on.</p></div><div className="map" aria-label="Map highlighting Nigeria and Cameroon" role="img"><div className="map__land" /><span className="map__nigeria">Nigeria</span><span className="map__cameroon">Cameroon</span><span className="map__pin">●</span></div><div className="regions__office"><p className="eyebrow">Head Office</p><h2>Nigeria</h2><p>Sanga Oil Limited<br />Head Office, Nigeria.</p><a className="button button--outline" href="#contact">Learn More About Us</a><div className="office-graphic" /></div></section>

    <footer className="footer" id="contact"><div className="wrap footer__grid"><div><Brand inverse /><p>Powering Performance.<br />Protecting Your Journey.</p></div><div><h2>Quick Links</h2><a href="#home">Home</a><a href="#about">About Us</a><a href="#products">Products</a><a href="#why">Why Sanga Oil</a><a href="#contact">Contact Us</a></div><div><h2>Products</h2><a href="#products">2T (TC-W3) API SL</a><a href="#products">4T (FC-W) API SM</a></div><div><h2>Contact Us</h2><p>⌖ &nbsp; 2 Life Avenue, Eliozu, Port Harcourt, Rivers State</p><p>☎ &nbsp; Phone: <em>Not provided</em></p><p>✉ &nbsp; Email: <a href="mailto:Support@sangaoils.com">Support@sangaoils.com</a></p><p>◎ &nbsp; Website: <em>Not provided</em></p></div></div><div className="wrap footer__bottom"><span>© 2024 Sanga Oil Limited. All rights reserved.</span><span>Quality Oil. Trusted Performance.</span></div></footer>
  </main>;
}

function ProductCard({ grade, formula, badge, api, equivalent, description }: { grade: "2T" | "4T"; formula: string; badge: string; api: string; equivalent: string; description: string }) { return <article className={`product-card product-card--${grade.toLowerCase()} reveal`}><ProductVessel grade={grade} /><div><span className="product-card__badge">{badge}</span><h3>{grade} <small>({formula})</small></h3><b>{api}</b><h4>{equivalent}</h4><p>{description}</p><div className="product-card__icons"><Icon>⚓</Icon><Icon>⚙</Icon><Icon>◈</Icon></div></div></article>; }
function Size({ name, copy, visual }: { name: string; copy: string; visual: "bottle" | "vessel" | "drum" }) { return <article><div className={`size-visual size-visual--${visual}`}>{visual === "vessel" && <ProductVessel grade="4T" size="small" />}{visual === "bottle" && <ProductVessel grade="2T" size="small" />}</div><div><b>{name}</b><p>{copy}</p></div></article>; }
